# exercise xp

# 🌟Exercise 1: Introduction to Data Analysis (Easy)


Qu'est-ce que l'analyse de données ?
L'analyse de données consiste à recueillir, interroger, traiter et faire parler les données en utilisant des langages de programmation comme Python et des langages de gestion de bases de données (comme le SQL), afin de guider et de faciliter la prise de décisions stratégiques.

Pourquoi l'analyse des données est-elle importante dans le contexte actuel ?
L'importance de l'analyse de données réside dans le besoin vital des entreprises de construire des produits ou des services parfaitement adaptés aux attentes de leurs utilisateurs. Cela n'est possible qu'à condition de comprendre précisément leur profil : ce qu'ils apprécient, ce qu'ils rejettent, ainsi que leurs caractéristiques intrinsèques (telles que l'âge, l'origine géographique, etc.).

Dans un monde où les informations circulent en continu et à grande vitesse, la capacité à exploiter efficacement cette masse de données confère un avantage concurrentiel absolu à l'organisation qui la maîtrise.

Trois domaines dans lesquels l'analyse des données est utilisée aujourd'hui
Le domaine des télécommunications : Les habitudes de consommation des clients y sont analysées en détail afin de leur proposer des offres personnalisées et un meilleur rapport qualité-prix.

Le domaine de l'agriculture 4.0 : Des modèles prédictifs sont développés pour optimiser le rendement des cultures, anticiper les besoins du sol et faire face efficacement aux aléas climatiques.

Le domaine du marketing : Les campagnes et contenus promotionnels sont élaborés sur mesure en ciblant des personas (profils

In [9]:
import pandas as pd
# 🌟Exercise 2: Dataset Loading and Initial Analysis

# Load the dataset into Jupyter or Google Colab.
df1 = pd.read_csv('TimeAmericansSpendSleeping.csv')
df2 = pd.read_csv('MentalHealthDepressionDisorderData.csv')
df3 = pd.read_csv('clean_dataset.csv')

print("--- DATASET 1 : How Much Sleep Do Americans Really Get? ---")
display(df1.head())
print(f"Dimensions : {df1.shape[0]} lignes et {df1.shape[1]} colonnes \n")

# 🌟 Étape 3 : Analyse du Dataset 2 (Mental Health)

print("\n--- DATASET 2 : Global Trends in Mental Health Disorder ---")
display(df2.head())
print(f" Dimensions : {df2.shape[0]} lignes et {df2.shape[1]} colonnes \n")

# 🌟 Étape  4: Analyse du Dataset 3 (Credit Card)

print("\n--- DATASET 3 : Credit Card Approvals ---")
display(df3.head())
print(f"Dimensions : {df3.shape[0]} lignes et {df3.shape[1]} colonnes")

--- DATASET 1 : How Much Sleep Do Americans Really Get? ---

C:\Users\USER\AppData\Local\Temp\ipykernel_40404\1101862602.py:6: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv('MentalHealthDepressionDisorderData.csv')

,index,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both

Dimensions : 945 lignes et 9 colonnes


--- DATASET 2 : Global Trends in Mental Health Disorder ---

,index,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,0,Afghanistan,AFG,1990,0.16056,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,1,Afghanistan,AFG,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,2,Afghanistan,AFG,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
3,3,Afghanistan,AFG,1993,0.160037,0.698257,0.094336,4.830864,1.705320,4.096190,0.669738
4,4,Afghanistan,AFG,1994,0.160022,0.698469,0.092439,4.829423,1.716069,4.099582,0.669260

 Dimensions : 108553 lignes et 11 colonnes


--- DATASET 3 : Credit Card Approvals ---

,Gender,Age,Debt,Married,BankCustomer,Industry,Ethnicity,YearsEmployed,PriorDefault,Employed,CreditScore,DriversLicense,Citizen,ZipCode,Income,Approved
0,1,30.83,0.000,1,1,Industrials,White,1.25,1,1,1,0,ByBirth,202,0,1
1,0,58.67,4.460,1,1,Materials,Black,3.04,1,1,6,0,ByBirth,43,560,1
2,0,24.50,0.500,1,1,Materials,Black,1.50,1,0,0,0,ByBirth,280,824,1
3,1,27.83,1.540,1,1,Industrials,White,3.75,1,1,5,1,ByBirth,100,3,1
4,1,20.17,5.625,1,1,Industrials,White,1.71,1,0,0,0,ByOtherMeans,120,0,1

Dimensions : 690 lignes et 16 colonnes

In [25]:
#  🌟Exercise 3: Identifying Data Types

df1.info()
print("\n")
print(df1.dtypes)
print("\n")
print(df1.nunique)

# On définit les colonnes par type
colonnes_quantitatives = ("Year", "Avg hrs per day sleeping", "Standard Error")
colonnes_qualitatives = ("Period", "Type of Days", "Age Group", "Activity", "Sex")
# Note : j'exclus 'index' car c'est un identifiant technique, souvent considéré comme qualitatif (étiquette).
print("--- JUSTIFICATIONS POUR LES DONNÉES QUANTITATIVES ---")
for col in colonnes_quantitatives:
    print(f"La colonne '{col}' est une donnée quantitative car elle représente une valeur numérique mesurable sur laquelle nous pouvons effectuer des calculs arithmétiques (comme une moyenne ou une somme).\n")

print("\n--- JUSTIFICATIONS POUR LES DONNÉES QUALITATIVES ---")
for col in colonnes_qualitatives:
    print(f"La colonne '{col}' est une donnée qualitative car elle décrit une catégorie ou une caractéristique non-numérique qui sert à classer les données plutôt qu'à les mesurer.\n")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 945 entries, 0 to 944
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   index                     945 non-null    int64
 1   Year                      945 non-null    int64
 2   Period                    945 non-null    object
 3   Avg hrs per day sleeping  945 non-null    float64
 4   Standard Error            945 non-null    float64
 5   Type of Days              945 non-null    object
 6   Age Group                 945 non-null    object
 7   Activity                  945 non-null    object
 8   Sex                       945 non-null    object
dtypes: float64(2), int64(2), object(5)
memory usage: 66.6+ KB


index                         int64
Year                          int64
Period                       object
Avg hrs per day sleeping    float64
Standard Error              float64
Type of Days                 object
Age Group                    object
Activity                     object
Sex                          object
dtype: object


<bound method DataFrame.nunique of      index  Year  Period  Avg hrs per day sleeping  Standard Error  \
0        0  2003  Annual                      8.57           0.018
1        1  2004  Annual                      8.55           0.026
2        2  2005  Annual                      8.62           0.023
3        3  2006  Annual                      8.63           0.024
4        4  2007  Annual                      8.57           0.024
..     ...   ...     ...                       ...             ...
940    940  2013  Annual                      8.83           0.085
941    941  2014  Annual                      8.98           0.086
942    942  2015  Annual                      8.83           0.074
943    943  2016  Annual                      8.92           0.071
944    944  2017  Annual                      8.81           0.091

            Type of Days          Age Group  Activity    Sex
0               All days  15 years and over  Sleeping   Both
1               All days  15 years and over  Sleeping   Both
2               All days  15 years and over  Sleeping   Both
3               All days  15 years and over  Sleeping   Both
4               All days  15 years and over  Sleeping   Both
..                   ...                ...       ...    ...
940  Nonholiday weekdays  65 years and over  Sleeping  Women
941  Nonholiday weekdays  65 years and over  Sleeping  Women
942  Nonholiday weekdays  65 years and over  Sleeping  Women
943  Nonholiday weekdays  65 years and over  Sleeping  Women
944  Nonholiday weekdays  65 years and over  Sleeping  Women

[945 rows x 9 columns]>
--- JUSTIFICATIONS POUR LES DONNÉES QUANTITATIVES ---
La colonne 'Year' est une donnée quantitative car elle représente une valeur numérique mesurable sur laquelle nous pouvons effectuer des calculs arithmétiques (comme une moyenne ou une somme).

La colonne 'Avg hrs per day sleeping' est une donnée quantitative car elle représente une valeur numérique mesurable sur laquelle nous pouvons effectuer des calculs arithmétiques (comme une moyenne ou une somme).

La colonne 'Standard Error' est une donnée quantitative car elle représente une valeur numérique mesurable sur laquelle nous pouvons effectuer des calculs arithmétiques (comme une moyenne ou une somme).


--- JUSTIFICATIONS POUR LES DONNÉES QUALITATIVES ---
La colonne 'Period' est une donnée qualitative car elle décrit une catégorie ou une caractéristique non-numérique qui sert à classer les données plutôt qu'à les mesurer.

La colonne 'Type of Days' est une donnée qualitative car elle décrit une catégorie ou une caractéristique non-numérique qui sert à classer les données plutôt qu'à les mesurer.

La colonne 'Age Group' est une donnée qualitative car elle décrit une catégorie ou une caractéristique non-numérique qui sert à classer les données plutôt qu'à les mesurer.

La colonne 'Activity' est une donnée qualitative car elle décrit une catégorie ou une caractéristique non-numérique qui sert à classer les données plutôt qu'à les mesurer.

La colonne 'Sex' est une donnée qualitative car elle décrit une catégorie ou une caractéristique non-numérique qui sert à classer les données plutôt qu'à les mesurer.

In [36]:
# 🌟Exercise 4: Exploring Data Types

df4 = pd.read_csv('Iris.csv')
print(df4.info)
print("---affichage de quelques lignes du db IRIS---\n")
print(df4.head())
print("---affichage des valeurs distinctes des colonnes du db IRIS---\n")
print(df4.nunique())
print("---type des colonnes---\n")
print(df4.dtypes)
qt_column = ("SepalLengthCm","SepalWidthCm","PetalLengthCm", "PetalWidthCm")
print("Les colonnes énumérées ci-dessous sont de type quantitatif car elles contiennent des valeurs mesurées; on peut donc calculer une moyenne par exemple")
for qt_c in qt_column:
    print(qt_c)

print("\n")

print("La colonne Species est une colonne de données qualitative car il s'agit d'une classification selon 3 espèces comme nous as montré l'instruction df4.nunique")

<bound method DataFrame.info of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]>
---affichage de quelques lignes du db IRIS---

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
---affichage des valeurs distinctes des colonnes du db IRIS---

Id               150
SepalLengthCm     35
SepalWidthCm      23
PetalLengthCm     43
PetalWidthCm      22
Species            3
dtype: int64
---type des colonnes---

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object
Les colonnes énumérées ci-dessous sont de type quantitatif car elles contiennent des valeurs mesurées; on peut donc calculer une moyenne par exemple
SepalLengthCm
SepalWidthCm
PetalLengthCm
PetalWidthCm


La colonne Species est une colonne de données qualitative car il s'agit d'une classification selon 3 espèces comme nous as montré l'instruction df4.nunique

In [37]:
# 🌟Exercise 5: Basic Observation Skills in Data Analysis

print("Nous avons déjà chargé ce dataset à l'exercice 2")
print(df1.head())
# Je note les observations comme des commentaires
# trend analysis
"""
Colonnes : Year et Avg hrs per day sleeping.
Justification : La colonne Year nous donne une séquence temporelle. On peut l'utiliser comme axe X pour voir si le temps de sommeil moyen (Avg hrs per day sleeping) augmente, diminue ou reste stable sur plusieurs années.
Question type : "Est-ce que les gens dorment globalement plus en 2017 qu'en 2003 ?"
"""
# group comparison
"""
Colonne : Sex
Justification : On peut comparer la moyenne de sommeil des hommes par rapport à celle des femmes pour identifier des disparités.
Question type : "Qui dort le plus en moyenne : les hommes ou les femmes ?"
"""

Nous avons déjà chargé ce dataset à l'exercice 2
   index  Year  Period  Avg hrs per day sleeping  Standard Error Type of Days  \
0      0  2003  Annual                      8.57           0.018     All days
1      1  2004  Annual                      8.55           0.026     All days
2      2  2005  Annual                      8.62           0.023     All days
3      3  2006  Annual                      8.63           0.024     All days
4      4  2007  Annual                      8.57           0.024     All days

           Age Group  Activity   Sex
0  15 years and over  Sleeping  Both
1  15 years and over  Sleeping  Both
2  15 years and over  Sleeping  Both
3  15 years and over  Sleeping  Both
4  15 years and over  Sleeping  Both

# 🌟 Exercise 6: Identifying Data Types
1. A company’s financial reports stored in an Excel file.
Réponse : Données structurées (Structured data)

Raisonnement : Un fichier Excel est organisé en lignes, en colonnes et en cellules avec des types de données précis (chiffres, dates, texte court). C'est le propre d'une structure tabulaire.

2. Photographs uploaded to a social media platform.
Réponse : Données non structurées (Unstructured data)

Raisonnement : Une image est un ensemble de pixels. Elle ne contient pas de structure interne native (comme un tableau) qui dit explicitement ce qu'elle représente. Pour un ordinateur, c'est un fichier brut.

3. A collection of news articles on a website.
Réponse : Données non structurées (Unstructured data)

Raisonnement : Même si les articles sont écrits avec des paragraphes, le texte libre (le langage naturel) est considéré comme non structuré car sa longueur varie et il n'est pas confiné dans des cases de base de données standard.

4. Inventory data in a relational database.
Réponse : Données structurées (Structured data)

Raisonnement : Une base de données relationnelle (SQL) utilise des tables strictes avec des clés primaires, des clés étrangères et des types de colonnes bien définis. C'est l'exemple parfait de la donnée structurée.

5. Recorded interviews from a market research study.
Réponse : Données non structurées (Unstructured data)

Raisonnement : Les enregistrements audio contiennent de la voix, des intonations, des bruits de fond et des silences. Il n'y a aucune structure tabulaire là-dedans; c'est un flux de données continu et complexe.

# 🌟 Exercise 7: Transformation Exercise

1. A series of blog posts about travel experiences.
Méthode proposée : Utiliser des techniques de NLP (Traitement du Langage Naturel) comme la Reconnaissance d'Entités Nommées (NER) et l'Analyse de Sentiment.

Raisonnement : Les articles de blog contiennent du texte libre. On peut programmer un script (en Python avec des bibliothèques comme spaCY ou via des API de LLM) pour extraire automatiquement des informations clés et les placer dans un tableau avec les colonnes suivantes : [Date de publication, Destination (Pays/Ville), Budget estimé, Note de satisfaction (Score de sentiment), Activités clés].

2. Audio recordings of customer service calls.
Méthode proposée : Appliquer une technologie de Speech-to-Text (Transcription Audio-Texte) suivie d'une extraction de mots-clés.

Raisonnement : Le son ne peut pas être analysé directement dans un tableau. On transforme d'abord l'audio en texte écrit (en utilisant des modèles comme Whisper d'OpenAI). Une fois le texte obtenu, on extrait des données pour remplir une base de données structurée contenant : [ID de l'appel, Durée de l'appel, Motif de la plainte (ex: Facturation, Panne), Résolution (Oui/Non), Sentiment du client].

3. Handwritten notes from a brainstorming session.
Méthode proposée : Utiliser une technologie d'OCR (Reconnaissance Optique de Caractères) intelligente, combinée à une classification par thèmes.

Raisonnement : L'OCR permet de scanner l'image ou le document d'origine pour convertir l'écriture manuscrite en texte numérique (comme le fait l'application Google Lens). Comme il s'agit d'un brainstorming, on peut ensuite structurer ce texte en classant les idées dans un tableau croisé ou une matrice à trois colonnes : [Catégorie/Projet, Idée émise, Porteur de l'idée].

4. A video tutorial on cooking.
Méthode proposée : Utiliser l'Analyse Vidéo Multimodale (extraction des pistes audio, des sous-titres et traitement d'images/Computer Vision).

Raisonnement : Une vidéo combine des images mobiles et du son. On extrait la recette en convertissant la voix du chef en texte pour obtenir les étapes. En parallèle, des algorithmes de vision par ordinateur peuvent détecter visuellement les ingrédients ou les ustensiles utilisés à l'écran. Au final, on transforme cette vidéo en une ligne de base de données structurée comme ceci : [Nom de la recette, Liste des ingrédients, Temps de cuisson, Ustensiles requis, Nombre d'étapes]

In [38]:
# 🌟 Exercise 8 : Import a file from Kaggle

print("Chargement du fichier")
df5 = pd.read_csv('train.csv')
print(df5.head())

Chargement du fichier
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

In [40]:
# Exercise 9 : Export a dataframe to excel format and JSON format.
# simple dataframe
data = {
    'Name': ['KOUADIO Josué', 'Anna', 'Peter', 'Linda'],
    'Age': [21, 34, 29, 32],
    'City': ['Abidjan', 'Paris', 'Berlin', 'London']
}
df = pd.DataFrame(data)

# exportation en fichier excel
df.to_excel('mydataframe_excel.xlsx', index=False)
# exportation en json
df.to_json('mydataframe_json.json', indent=4)

In [42]:
#🌟 Exercise 10: Reading JSON Data

# Import the JSON data from the provided URL.
url_zip = "https://github.com/devtlv/Datasets-DA-Bootcamp-2-/raw/refs/heads/main/Week%204%20-%20Data%20Understanding/W4D3%20-%20Importing%20Data,%20Exporting%20D/posts.zip"

# Use Pandas to read the JSON data.
df_json = pd.read_json(url_zip, compression='zip')

# Display the first five entries of the data.
df_json.head(5)

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...